openedx/.github

.editorconfig
.github/workflows/pr-automerge-open-release.yml
workflow-templates/pr-automerge-open-release.yml

Generally, we want to use reusable workflow rather than workflow templates.  Templates copy code around, making it hard to maintain.
This changes the action to use a hard-coded list of merge approvers.
Also, I updated the actions to latest versions, and used a more typical yaml syntax.

build: convert pr-automerge-open-release.yml to a reusable workflow

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/depr-ticket.yml
.github/workflows/add-depr-ticket-to-depr-board.yml
workflow-templates/add-depr-ticket-to-depr-board.yml

@feanil 
Note that the issue template will work for repos that haven't defined their own templates. Once a repo does have its own templates, they'll need to pull this one in explicitly.
You can see the template in action at https://github.com/openedx/tcril-onboarding/issues/new/choose and view the results of this action on the Actions tab. The most recent changes to the workflow were to explicitly test for the conditional on the `if` clause each time so no actions run if the ticket isn't DEPR. I tried using `if: ${{ success() }}` but for whatever reason, the first step is considered a success even if it doesn't run. Shrug.

Add depr issue template & work flow

---

.github/workflows/lockfileversion-check.yml
workflow-templates/lockfileversion-check.properties.json
workflow-templates/lockfileversion-check.yml

`lockfileVersion` value for the package-lock.json generated by NPM6 is **1** but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is **2**. So here we're going to check the lockfileVersion in package-lock.json in order to verify that dependencies were installed using NPM8.
We've added this workflow under edx organisation as well. Here's the [PR](https://github.com/edx/.github/pull/22)

feat: Added workflow for lockfileVersion check

---

workflow-templates/upgrade-python-requirements.yml

so extra quotes here is unnecessary & in fact causes bugs!
see https://github.com/openedx/docs.openedx.org/pull/135#issuecomment-1251146158 for step-by-step explanation of what this fixes; after this PR you would expect the final screengrab to not have two sets of quotes nested within one another any more

fix: interpolation of default branches comes with quotes

---

.github/workflows/upgrade-python-requirements.yml

This makes the openedx/.github workflow the same as the edx/.github workflow.

style: put a space between sentences

---

.github/workflows/upgrade-python-requirements.yml

- After the new release of `checkout@v2.5.0` the requirements upgrade PR started failing in all repos.
- The error was able to be reproduced with replicating the if condition in a test [PR](https://github.com/openedx/edx-rest-api-client/pull/237). 
- After fixing and testing the fix on local, now creating the PR to test this change in the upgrade requirements workflows by triggering a custom workflow build against the updated workflow.
- Since the PR has been created against a fork so this commit hash or branch name can't be used in any workflow that's why we need to merge the change to test it properly in other requirements upgrade actions.

fix: Update bash command to fix reusable workflow failure

---

.github/workflows/add-depr-ticket-to-depr-board.yml

Upgrade tibdex dependency to pull in the node 16 upgrade, as Actions are deprecating node 12. Tested and working for the BTR workflow: https://github.com/orgs/openedx/projects/28

chore: upgrade depr workflow tibdex dependency

---

.github/ISSUE_TEMPLATE/depr-ticket.yml

Update the DEPR issue template date fields and guidance as
follows:
* Remove "Technology Removal Date".
* Replace "First" with "Earliest" in "First Open edX Named Release Without This Functionality".
* Rename "Ticket Acceptance Date" to "Target Ticket Acceptance Date"
* Update descriptions to match. Provide named releases and cut date examples.
Notes: 
* These decisions were discussed and approved in https://github.com/openedx/open-edx-proposals/issues/333.
Todo:

docs: update DEPR issue date fields and guidance

---

.github/workflows/upgrade-python-requirements.yml

Use bash parameter expansion[1] for the DEFAULT_BRANCH fallback.  This should avoid other syntax gotchas once and for all.
[1] https://wiki.bash-hackers.org/syntax/pe#use_a_default_value
[This comment](https://github.com/openedx/.github/pull/33/files#r1032074481) links to [the failure](https://github.com/edx/edx-e2e-tests/actions/runs/3544876433/jobs/5952541056#step:2:2) this intends to fix.

fix: Default branch fallback

---

.github/workflows/update-browserslist-db.yml
workflow-templates/update-browserslist-db.properties.json
workflow-templates/update-browserslist-db.yml
workflow-templates/update-browserslist.properties-db.json

This PR fixes the issues of consumers of this workflow [crashing](https://github.com/openedx/frontend-app-account/actions/runs/3731200392) because secrets were not [provided](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets)

fix: added required secret in workflow

---

.github/workflows/add-depr-ticket-to-depr-board.yml

GitHub is removing the ProjectNext API on 12/31/2022.  These changes parallel the ones we made to fix add-GHrequest-to-team-board.yml in tcril-engineering:
https://github.com/openedx/tcril-engineering/compare/1e2bb7e..76ee9ea

refactor: update add-depr-ticket from ProjectNext to ProjectV2

---

.github/ISSUE_TEMPLATE/blank-issue.md

We would like to get to a place where every repo has a maintainer that triages incoming issues. Although the maintainership pilot [1] is chugging along, we are not there yet.
So, in the meantime, issue submitters should be warned that they may not get a response unless they cross-post to the forums.
[1] https://openedx.atlassian.net/wiki/spaces/COMM/pages/3426844690/Maintainership+Pilot

docs: add warning to blank issue template

---

.github/dependabot.yml

Our github actions build on top of various ones from the community but
we don't have a mechanism for updating those yet.  Use the built-in
capabilities of dependabot to create PRs in this repo for updates to our
action dependencies.

feat: Auto make PRs to update versions of dependent github actions.

---

profile/README.md

We don't want to promote it anymore.

docs: Remove devstack from the list.

---

workflow-templates/add-new-issues-to-a-project.yml

Update the template to not have any spaces in the job name.

fix: Job IDs can't have spaces.

---

docs/decisions/0001-shellcheck.rst
docs/decisions/0001-shellcheck.rst.bak

https://github.com/kdmccormick/openedx.github/blob/kdmccormick/shellcheck/docs/decisions/0001-shellcheck.rst
Draft .github PR to implement a shared workflow/template/action:
* https://github.com/openedx/.github/pull/64
Draft edx-platform PR, with the ShellCheck workflow in action:
* https://github.com/openedx/edx-platform/pull/31809

docs: add ADR to adopt ShellCheck

---

.github/workflows/lockfileversion-check-v3.yml
workflow-templates/lockfileversion-check-v3.properties.json
workflow-templates/lockfileversion-check-v3.yml

With move to node v18 and NPM9, the `lockfileVersion` is set to 3. Added a workflow to verify NPM9 is used to generate `package-lock` file by ensuring `lockfileVersion` is set to 3. Once node upgrade to v18 is complete across all MFEs, older version of the workflow which is checking for `lockVersion` 2 can be phased out.

feat: Added workflow for lockfileVersion 3 check

---

.github/workflows/repo-health-job.yml

- We want the input values to be all in strings so it'll be easier to pass these through the GITHUB Variables and Context variables to the reusable workflow.
- The string input parameter will be typecasted to number later on within the bash script if needed.

fix: update repo health workflow parameter type

---

.github/ISSUE_TEMPLATE/depr-ticket.yml

Update the named releases on the DEPR issue template, and update the default date format to be more standard.

fix: update depr-ticket.yml named releases

---

CONTRIBUTING.md

* splits up a run-on sentence
* removes link to wiki homepage, which I've accidentally clicked a few times now instead of clicking the link to the contribution guidelines

docs: minor rewording of CONTRIBUTING.md

---

.github/workflows/upgrade-python-requirements.yml
workflow-templates/upgrade-python-requirements.yml

Make the version of python we use for running `make upgrade`
configurable by the workflow user.
Prompted by https://github.com/openedx/openedxstats/pull/197 and relates to https://github.com/openedx/openedxstats/pull/200

feat: Be able to support other python versions for make upgrade.

---

SECURITY.md

With the acceptance of [OEP-60](https://github.com/openedx/open-edx-proposals/blob/master/oeps/processes/oep-0060-proc-sec-group.rst), the security policy should accurately reflect the separation of security processes between the Open edX community and edX. 
The new security policy is specific to the Open edX process, and includes an updated email address for reporting security vulnerabilities.

docs: update security.md policy to reflect Open edX policy

---

.github/workflows/merge-python-requirements-upgrade-prs.yml

- The reusable workflow was added in the https://github.com/openedx/.github/pull/77
- The workflow triggering [fails](https://github.com/edx/.github/actions/runs/5045122890) when being called from `edx` organisation due to the wrong file path issue.
- The custom parameter `github.repository` in the script path [changes](https://github.com/edx/.github/actions/runs/5045122890/jobs/9048997498#step:5:3) the file path to `edx` in our case whereas the correct path should always be `openedx/.github` instead.
- Updated the script download step to always download the script from the `openedx/.github` repo where it originally resides.

build: fix script download path for reusable workflow

---

.github/workflows/commitlint.yml

GitHub is going to stop supporting this insecure approach at some undefined future date:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I don't think there's much benefit in keeping this separated as two steps, so instead of using `GITHUB_OUTPUT` we can just make it a single step.

feat: Stop using deprecated ::set-output in commitlint workflow

---

workflow-templates/repo-health-workflow.yml

- Updating the template workflow under the final touches for the issue https://github.com/edx/edx-arch-experiments/issues/66
- The template workflow has been updated according to the successfully working workflow file in the edx/repo-health-data (private edx repo).

build: update repo health job template trigger workflow

---

workflow-templates/npm-publish.yml

This will default any new packages that try to publish to a set of
tokens that can publish to the `openedx` scope.  It also updates the
template to use the version of Node from `.nvmrc` instead of hardcoding
to Node 12

feat: Update the npm publish workflow template.

---

workflow-templates/npm-publish.yml

We changed the names for the secrets to be more generic than NPM because
they are being used for semantic release of other libraries to other
package systems as well.

fix: Update npm release workflow template.

---

.github/workflows/commitlint.yml

On a recent PR of mine, [the commitlint check was failing](https://github.com/openedx/frontend-platform/actions/runs/7254831382/job/19764334943?pr=619) because of an error in the workflow:
```
error running commitlint
require() of ES Module /github/workspace/commitlint.config.js from /node_modules/@commitlint/load/node_modules/cosmiconfig/dist/loaders.js not supported.
commitlint.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename commitlint.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in …
```

fix: commitlint fails if run in a repo that uses ES6 modules

---

.github/workflows/repo-health-job.yml

This pull request introduces a straightforward enhancement by incorporating a parameter(`repo_health` or `dependencies_health`) to facilitate the execution of the workflow script based on a specified parameter. Extensive testing has been conducted through custom fork execution in the repo-health-data, validating the robustness of this addition.
Related Issue: https://github.com/edx/edx-arch-experiments/issues/231

fix: Reuseability added for dependencies dashboard.

---

.github/workflows/bulk_repo_update.yml

- Copying the internal 2U tool over to Open edX side as well so community can use it to perform bulk upgrades in the future.
- Required secrets of the workflow are already configured in the `openedx` org and are being used in the scheduled requirements upgrade jobs so we don't need to add any new secrets in github env.

build: add bulk repo update workflow for openedx

---

.github/workflows/upgrade-python-requirements.yml

Description:
- This is to stop the workflow to send notification on requirement unchanged.
Note:
If we want to have specific output for this case, we can add additional output on https://github.com/openedx/testeng-ci/blob/ed9083cd6f0a774d5de75cefd356ad69dd47b9bf/jenkins/pull_request_creator.py#L224. However, I think this should be enough.

chore: stop sending notification for update python requirements on unchanged

---

profile/README.md

This edits the blurb on our [GH homepage](https://github.com/openedx/).
Tutor is definitely the community-supported distribution, but we're not cleared to describe it as "official".
(FWIW I originally wrote this, way back before I realized that)

docs: change tutor language

---

.github/workflows/commitlint.yml

Reverts openedx/.github#124
Reverting this, because it seems to be causing some issues, https://github.com/openedx/edx-lint/actions/runs/8604287415/job/23578582410
We can re-introduce it when we have more time to test/debug what's going on here.

Revert "build(deps): bump wagoid/commitlint-github-action from 5 to 6"

---

workflow-templates/pypi-publish.yml

The action now publishes versions and the master branch will stop
getting updates.  Also `__token__` is the default username so no need to
set it explicitly.

build: Update workflow template for PyPI Publishing.

---

.github/workflows/upgrade-python-requirements.yml

- With the updated package `lxml>5.0`, now the system dev packages are necessary to run `pip-compile`. Without installing dev packages `libxml2-dev` and `libxslt-dev`, the `requirements upgrade job` fails with following stack trace: 
See example failure build [error stack trace](https://github.com/openedx/edx-platform/actions/runs/8883842771/job/24391571930#step:5:433).
```
Collecting lxml (from -r requirements/edx-sandbox/base.in (line 5))
Downloading lxml-5.2.1.tar.gz (3.7 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 11.3 MB/s eta 0:00:00
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: …
```

build: update requirements upgrade workflow

---

profile/README.md

The old /edx/ org link goes the accidental edx-platform fork, oops.
(yes, I'm retconning "CMS")

docs: fix edx-platform link and expand acronyms

---

.github/workflows/bulk_repo_update.yml
.github/workflows/upgrade-python-requirements.yml

testeng-ci is deprecated in favor of repo-tools.
See the DEPR [1] and the PR that moved pull_request_creator to repo-tools [2].
This also includes some cosmetic changes to the upgrade PRs.
Before:
* branch == jenkins/upgrade-python-requirements-{id}
* title  == Python Requirements Update
* commit == chore: Updating Python Requirements
After:
* branch == repo-tools/upgrade-python-requirements-{id}
* title  == chore: Upgrade Python requirements
* commit == chore: Upgrade Python requirements
NOTE: This leaves behind a testeng-ci reference in the repo-health job. We need to figure out the future of the edx-repo-health repo. This will be a future task [3]
[1] https://github.com/openedx/public-engineering/issues/265
[2] https://github.com/openedx/repo-tools/pull/517
[3] …

feat: use pull request creator from repo-tools, not testeng-ci

---

profile/README.md

Surprised we didn't do this already

docs: mention the wiki in the org-wide readme

---

.github/workflows/update-browserslist-db.yml

The existing `update-browserslist-db` GitHub Action workflow file (often used by Open edX's shared JS libraries and MFEs) is not properly auto-merging, which results in stale data consumed by `browserslist`. I believe this is largely due to the lack of auto-approving the generated PR, which prevents it from passing branch protections on default branches.
This PR updates the workflow file as follows:
* No longer runs Node 16, instead relying on `.nvmrc` files defined in the consuming repo.
* Added a step to auto-approve the generated pull request (previously not included; not sure if the auto-merge ever really worked as a result?).
* Replaces the previous auto-merge step to instead rely on the `gh` CLI directly, per the documentation in `peter-evans/enable-pull-request-automerge` ([see …

fix: refactor update-browserslist-db to auto-approve PR and auto-merge with `gh` CLI

---

.github/workflows/update-browserslist-db.yml

On a run of the recent changes to `update-browserslist-db`, it was [observed](https://github.com/openedx/frontend-app-admin-portal/actions/runs/12639940401/job/35219310415) that when no diff is created when updating the `browserslist` DB, we correctly skip the "auto-approve" step, but still attempt to run the "enable auto-merge" step, resulting in an error as there is not a valid PR number generated without a diff.
Note: this no diff case will occur any time the workflow is run without any changes the `browserslist` DB (e.g., on consecutive runs).

fix: only enable automerge when PR is created in `update-browserslist-db`

---

.github/workflows/commitlint.yml

Fixes the workflow piece of https://github.com/openedx/.github/issues/163
If this lands before https://github.com/openedx/edx-lint/pull/486 it will break things. Once that lands I will move this out of draft.

fix: update commitlint workflow to check for and download config as `.mjs`

---

.github/ISSUE_TEMPLATE/depr-ticket.yml

Updated DEPR issue template dates to better
reflect the updated timeline recommendations
in OEP-21 for DEPR.
See https://github.com/openedx/open-edx-proposals/blame/master/oeps/processes/oep-0021-proc-deprecation.rst#L207-L218
These are dates in the current template:
- Proposal Date
- Target Ticket Acceptance Date
- Earliest Open edX Named Release Without This Functionality
Here are some proposed replacements:
- RFC Start Date
- Target Plan Accepted Date
- Target Transition Unblocked Date
- Earliest Breaking Changes Unblocked Date
- Earliest Open edX Named Release with Breaking Changes

fix: update github DEPR issue template

---

.github/ISSUE_TEMPLATE/depr-ticket-fast-track.yml
.github/ISSUE_TEMPLATE/depr-ticket.yml

Adds a Fast-Track DEPR issue template as described in https://github.com/openedx/.github/issues/175
https://github.com/openedx/.github/blob/kdmccormick/fast-track-depr/.github/ISSUE_TEMPLATE/depr-ticket-fast-track.yml

feat: Introduce Fast-Track DEPR Template

---

.github/workflows/add-to-cc-board.yml

This PR adds the action to add an issue or PR to a CC board. This is a reusable action. Follows the 
[technical discovery](https://docs.google.com/document/d/1uCfu-hyDG7U_dL9E3LTO7R560_eGya03M4MVMZHwH3c/edit?tab=t.0#heading=h.ibtgcqo5je5q) with some changes:
- We avoided using an external file to retrieve the board. We used a variable in the action to specify the board, and we placed the board numbers in the action. This was because it was very complicated to read a file in a reusable action.
- A token with the `projects` scope is required, the `GITHUB_TOKEN` does not have this scope
- Github issue: https://github.com/openedx/wg-coordination/issues/157
- Technical discovery: https://docs.google.com/document/d/1uCfu-hyDG7U_dL9E3LTO7R560_eGya03M4MVMZHwH3c/edit?usp=sharing
- Internal ticket: …

feat: Action to add an issue or PR to a CC board

---

LICENSE.txt

This repo falls under one of the categories we use Apache 2.0 licenses for:
Repos for broad-interest or developer tools that are not
unique to the Open edX platform and do not run as part of
the Open edX platform.

chore: add Apache 2.0 license

---

.github/ISSUE_TEMPLATE/depr-ticket-fast-track.yml

Eventually, we update use the GitHub workflow to recognize Fast-Track DEPR issues and apply the correct status & notification routing. In the meantime, though, we're just adding more instructions here so that contributors can follow the process themselves.
Additionally, we add some default values to the Dates fields in order to make it clear what's going on in relation to the standard DEPR process.
These values could be used in the future as keyphrases to trigger the right GitHub workflow jobs.
Preview: https://github.com/openedx/.github/blob/kdmccormick/fast-track-2/.github/ISSUE_TEMPLATE/depr-ticket-fast-track.yml

docs: Add more instructions to the Fast-Track DEPR template

---

.github/ISSUE_TEMPLATE/depr-ticket.yml

Make the two task lists at the bottom more clear.  Them having the same name made them less useful after the DEPR is created and the form context is not provided.

docs: Update issue template
